version: "3"
services:
    web:
    # replace username/repo:tag with your name and image details
    image: jheron/feflask:v1
    environment:
      PASSWORD: secret
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - webnet
  #  postgres:
  #  image: postgres
  #  environment:
  #    POSTGRES_PASSWORD: secret
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - /home/docker/data:/data
  #  deploy:
  #    placement:
  #      constraints: [node.role == manager]
  #  networks:
  #    - webnet
networks:
  webnet:
